spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: ${DATA_URL}
    username: ${DATA_ID}
    password: ${DATA_PWD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace

jwt:
  header: Authorization
  
  secret: ${JWT_SECRET}
  token-validity-in-seconds: ${JWT_TIME}